version: '3.8'

services:
  ghost:
    image: ghost:latest
    restart: unless-stopped
    ports:
      - "2368:2368"
    environment:
      # Database configuration
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      database__useNullAsDefault: 'true'
      
      # Production URL - Update this with your domain
      url: ${GHOST_URL:-https://your-domain.com}
      
      # Production environment
      NODE_ENV: production
      
      # Mail configuration (optional)
      mail__transport: SMTP
      mail__options__service: ${MAIL_SERVICE:-}
      mail__options__auth__user: ${MAIL_USER:-}
      mail__options__auth__pass: ${MAIL_PASS:-}
      
    volumes:
      - ./ghost_content:/var/lib/ghost/content
      
  # Optional: Add nginx for SSL termination
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ghost
    profiles:
      - nginx

networks:
  default:
    name: ghost-network