version: 3
services:
  ghost:
    image: ghost:5-alpine
    environment:
      NODE_ENV: production
      url: ${{RAILWAY_PUBLIC_DOMAIN}}
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      mail__transport: Direct
      logging__transports__0: stdout
      privacy__useUpdateCheck: false
    volumes:
      - ghost_content:/var/lib/ghost/content
    ports:
      - "2368"

volumes:
  ghost_content: