services:
  ghost:
    image: ghost:latest
    restart: unless-stopped
    ports:
      - "2368:2368"
    environment:
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      database__useNullAsDefault: 'true'
      url: http://localhost:2368
      NODE_ENV: development
    volumes:
      - ./ghost_content:/var/lib/ghost/content